{{- $root := . }}
{{- if .Values.externalSecrets }}
{{- range .Values.externalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name | quote }}
  namespace: {{ .namespace | quote }}
  labels:
    {{- include "externalSecretsWrapper.labels" $root | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | quote }}
  secretStoreRef:
    name: {{ .secretStoreRef.name | quote }}
    kind: {{ .secretStoreRef.kind | quote }}
  target:
    name: {{ .target.name | quote }}
    creationPolicy: {{ .target.creationPolicy | quote }}
    deletionPolicy: {{ .target.deletionPolicy | quote }}
    template:
      engineVersion: {{ default "v2" .target.engineVersion | quote }}
      mergePolicy: {{ default "Replace" .target.mergePolicy | quote }}
      type: {{ .target.templateType | quote }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        conversionStrategy: {{ default "Default" .remoteRef.conversionStrategy | quote }}
        decodingStrategy: {{ default "None" .remoteRef.decodingStrategy | quote }}
        key: {{ .remoteRef.key | quote }}
        metadataPolicy: {{ default "None" .remoteRef.metadataPolicy | quote }}
        nullBytePolicy: {{ default "Ignore" .remoteRef.nullBytePolicy | quote }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property | quote }}
        {{- end }}
    {{- end }}
---
{{- end }}
{{- else if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name | quote }}
  namespace: {{ .Values.externalSecret.namespace | quote }}
  labels:
    {{- include "externalSecretsWrapper.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | quote }}
  target:
    name: {{ .Values.externalSecret.target.name | quote }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy | quote }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy | quote }}
    template:
      engineVersion: {{ default "v2" .Values.externalSecret.target.engineVersion | quote }}
      mergePolicy: {{ default "Replace" .Values.externalSecret.target.mergePolicy | quote }}
      type: {{ .Values.externalSecret.target.templateType | quote }}
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        conversionStrategy: {{ default "Default" .remoteRef.conversionStrategy | quote }}
        decodingStrategy: {{ default "None" .remoteRef.decodingStrategy | quote }}
        key: {{ .remoteRef.key | quote }}
        metadataPolicy: {{ default "None" .remoteRef.metadataPolicy | quote }}
        nullBytePolicy: {{ default "Ignore" .remoteRef.nullBytePolicy | quote }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property | quote }}
        {{- end }}
    {{- end }}
{{- end }}
