productionChecks:
  enabled: false

namespaces:
- mongodb-7
- mysql-8
- mysql-5-7
- mysql-5-1-legacy
- postgresql-16
- redis

external-secrets:
  installCRDs: false
  leaderElect: true
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 750m
      memory: 768Mi
  webhook:
    create: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  certController:
    create: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

vaultStore:
  enabled: true
  name: "databases"
  kind: ClusterSecretStore
  provider:
    server: "https://host.docker.internal:8200"
    path: "databases"
    version: "v2"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ4ekNDQTYrZ0F3SUJBZ0lVZThhbE1HbFJpNStnMzhKejdjS2tEazZxeFZvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2N6RUxNQWtHQTFVRUJoTUNTVVF4RURBT0JnTlZCQWdNQjBwaGEyRnlkR0V4RURBT0JnTlZCQWNNQjBwaAphMkZ5ZEdFeEZEQVNCZ05WQkFvTUMweHZZMkZzSUZaaGRXeDBNUkV3RHdZRFZRUUxEQWhRYkdGMFptOXliVEVYCk1CVUdBMVVFQXd3T1RHOWpZV3dnVm1GMWJIUWdRMEV3SGhjTk1qWXdOakF6TURZMU9ESTJXaGNOTXpZd05UTXgKTURZMU9ESTJXakJ6TVFzd0NRWURWUVFHRXdKSlJERVFNQTRHQTFVRUNBd0hTbUZyWVhKMFlURVFNQTRHQTFVRQpCd3dIU21GcllYSjBZVEVVTUJJR0ExVUVDZ3dMVEc5allXd2dWbUYxYkhReEVUQVBCZ05WQkFzTUNGQnNZWFJtCmIzSnRNUmN3RlFZRFZRUUREQTVNYjJOaGJDQldZWFZzZENCRFFUQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dJUEFEQ0NBZ29DZ2dJQkFNZTJRRTV5N3ZBZWpWa2JYQm5UN2pKSDlrdHJ4bXRTUXFtdGQrVWtjdmNIQ3FUUwowaENLRlBNUWhZbjhkVWtWcTFvRHFoOGpuMFNES0F1WXF1eDdVMkRzK3VIbXJBUnBXS0ZGcnBNTnA4VVlwZFQ5CjJTSHVzL3dlSWhDejZnWW43RkFIanl6Snc4RHZiaG1pN0UrSHgrVjRhTGxlbWk3VDQyOGR6QW8wVFJmaUgzUmMKQytMaHJFUkNQaVVSSVZtd0djV2l0eTlQWmwvM1lxWEFqQjZXTW8yaS93L09sT2JjWlRydCsxQnhqUEliUnhYVQpHY2U0ei9ySkQ5UHZqVTdsNVp3REV0YVNjd0Q1ekpTRFY1bnlhcXBtamdxWFNnZVFOOWtZL0JwQlAxTitZUFBaCkp5U0RNY3Y4dkF2WG5YRjQwTzJoTGpuL0hwQ09rM0x4aDMwR2l2cFBLSEVXdzhHQWVPaU15WGdCclkzb0tvekMKeFB5bFdIZm02YjRRV2N3Y1V1RzhjL05xdXljbGkxREl5cmUrc1VsaTNXUGc5R1pGTGlQN0NibGdSaUxFeU1vNApBbENoVmNBL3NCMmFjWGJ4RVdMRENTNWx6cTBaMXZuZzYrTDBwTE5SQ3cydmxXU2xHanpKTmJ5bWdvRUN3RlNOCktiaytFWEtVT256MmpEYmhva2VFUkxxRXR4RjNMMStCLzVhWmFpSDc2TE5xMFUrQndUSnFKOVdKMjdpREl2QnEKdWs2UDVaUkVrakRCYlZwb2tQMnJteVN0NGVRRnpYMzQvUXQzMkFHZm9wWGpLUzhWc1I1VWtxTUV4L2ZkYjd1cAo4U2R0YnZuRStZOVFUWGkrSTBQUlpFN3ZqdFVhRWw0dXkrQm5TengvSmkweW04Q1BBZVBQM0FOeC9yeWRBZ01CCkFBR2pVekJSTUIwR0ExVWREZ1FXQkJRRU9yYXlzQUxJR1FTdW9CNHhlSlZVMUwvTVREQWZCZ05WSFNNRUdEQVcKZ0JRRU9yYXlzQUxJR1FTdW9CNHhlSlZVMUwvTVREQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUNBUUIvWUV0dWduNTVybW1ITUNrekJzVGpoL21YZlFOcFdTLzR6THJXRFppdnZEMTg4dXZDClJIeUk2bEZhSGd0b1BodUxjbXlzTGJidXBsaWF5cHJKZDZzT1g2bjk3QXZTZEthOG1ERE1Jamx3Q1pxRS9oNisKMlA0d3FMMUdPMEFQc3RablN0aks1d2RaSUpqaEJVa3AyUGNzc0RkUFRjVlVsK1JxdCtPMTRFQzBhVFBDQ1hFSwp4OUpvdC9SUlJCdWJJK25sVyswNndKUUlCSndidnZZWDFqOS8yNjJQQ2I3aTVTWkU5a0Ztb3BIL0F1dlkzeFBzCnQyOXFHRkh0NFRKYWFTeWlXcDFiT3Q1dDZnOHY5WnZUOGxKL295dkJISTVSQ3J1NUI4WXdHeUlRbWtvZVBwVkoKU1FQRzFEMElGK2tpbGxHb010czVUQ0FmZUlaeUFHZEZhb3NiSk96Z1lHUVI5VkFXZFRmSURQd3F2em1jc1VzWApqWU5pZW52K0xySzJNL2dXNmRPb25RUzZra3NjaUFPUFlXT2M3Y2xaUlJYa2JPRjkwa25hWXJib3ljcHlvbmxtCmU2NnFJNVpyOUxIc3ZpV3NHYitQd1B3TUt6KzdjbGpLWVlGd1JDQ3NWTUxoU2JNNElXRUN5a2tuT0J1OFROOCsKelNjTmpLL2hYZ0Q2bGM3QlJreVR0YkVVMzZCRzcxRHdsNVMxSXB5TXhiUHljdnRWaVRkYkEveXVLNVVuN3pBWAp2UzFIL0NrVVBUWStkbUZ0SmhlNEhkTXlTYkZqa2FzQzN2UzZZa2UxNWloejNBaWxBQ0cwbDZYanVLU1NRSWNRCjZOVGE4U3V0OXdkcFBOSUhPalV3S1prWVdjaGNhblkwck1HU044QjVWSCtqUWhHWVIzeHFKUjZqQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  auth:
    kubernetes:
      mountPath: "kubernetes-local"
      role: "external-secrets"
      serviceAccountRef:
        name: "external-secrets"
        namespace: "external-secrets"

vaultStoreApps:
  enabled: true
  name: "prohukum-apps"
  kind: ClusterSecretStore
  provider:
    server: "https://host.docker.internal:8200"
    path: "prohukum-apps"
    version: "v2"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ4ekNDQTYrZ0F3SUJBZ0lVZThhbE1HbFJpNStnMzhKejdjS2tEazZxeFZvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2N6RUxNQWtHQTFVRUJoTUNTVVF4RURBT0JnTlZCQWdNQjBwaGEyRnlkR0V4RURBT0JnTlZCQWNNQjBwaAphMkZ5ZEdFeEZEQVNCZ05WQkFvTUMweHZZMkZzSUZaaGRXeDBNUkV3RHdZRFZRUUxEQWhRYkdGMFptOXliVEVYCk1CVUdBMVVFQXd3T1RHOWpZV3dnVm1GMWJIUWdRMEV3SGhjTk1qWXdOakF6TURZMU9ESTJXaGNOTXpZd05UTXgKTURZMU9ESTJXakJ6TVFzd0NRWURWUVFHRXdKSlJERVFNQTRHQTFVRUNBd0hTbUZyWVhKMFlURVFNQTRHQTFVRQpCd3dIU21GcllYSjBZVEVVTUJJR0ExVUVDZ3dMVEc5allXd2dWbUYxYkhReEVUQVBCZ05WQkFzTUNGQnNZWFJtCmIzSnRNUmN3RlFZRFZRUUREQTVNYjJOaGJDQldZWFZzZENCRFFUQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dJUEFEQ0NBZ29DZ2dJQkFNZTJRRTV5N3ZBZWpWa2JYQm5UN2pKSDlrdHJ4bXRTUXFtdGQrVWtjdmNIQ3FUUwowaENLRlBNUWhZbjhkVWtWcTFvRHFoOGpuMFNES0F1WXF1eDdVMkRzK3VIbXJBUnBXS0ZGcnBNTnA4VVlwZFQ5CjJTSHVzL3dlSWhDejZnWW43RkFIanl6Snc4RHZiaG1pN0UrSHgrVjRhTGxlbWk3VDQyOGR6QW8wVFJmaUgzUmMKQytMaHJFUkNQaVVSSVZtd0djV2l0eTlQWmwvM1lxWEFqQjZXTW8yaS93L09sT2JjWlRydCsxQnhqUEliUnhYVQpHY2U0ei9ySkQ5UHZqVTdsNVp3REV0YVNjd0Q1ekpTRFY1bnlhcXBtamdxWFNnZVFOOWtZL0JwQlAxTitZUFBaCkp5U0RNY3Y4dkF2WG5YRjQwTzJoTGpuL0hwQ09rM0x4aDMwR2l2cFBLSEVXdzhHQWVPaU15WGdCclkzb0tvekMKeFB5bFdIZm02YjRRV2N3Y1V1RzhjL05xdXljbGkxREl5cmUrc1VsaTNXUGc5R1pGTGlQN0NibGdSaUxFeU1vNApBbENoVmNBL3NCMmFjWGJ4RVdMRENTNWx6cTBaMXZuZzYrTDBwTE5SQ3cydmxXU2xHanpKTmJ5bWdvRUN3RlNOCktiaytFWEtVT256MmpEYmhva2VFUkxxRXR4RjNMMStCLzVhWmFpSDc2TE5xMFUrQndUSnFKOVdKMjdpREl2QnEKdWs2UDVaUkVrakRCYlZwb2tQMnJteVN0NGVRRnpYMzQvUXQzMkFHZm9wWGpLUzhWc1I1VWtxTUV4L2ZkYjd1cAo4U2R0YnZuRStZOVFUWGkrSTBQUlpFN3ZqdFVhRWw0dXkrQm5TengvSmkweW04Q1BBZVBQM0FOeC9yeWRBZ01CCkFBR2pVekJSTUIwR0ExVWREZ1FXQkJRRU9yYXlzQUxJR1FTdW9CNHhlSlZVMUwvTVREQWZCZ05WSFNNRUdEQVcKZ0JRRU9yYXlzQUxJR1FTdW9CNHhlSlZVMUwvTVREQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUNBUUIvWUV0dWduNTVybW1ITUNrekJzVGpoL21YZlFOcFdTLzR6THJXRFppdnZEMTg4dXZDClJIeUk2bEZhSGd0b1BodUxjbXlzTGJidXBsaWF5cHJKZDZzT1g2bjk3QXZTZEthOG1ERE1Jamx3Q1pxRS9oNisKMlA0d3FMMUdPMEFQc3RablN0aks1d2RaSUpqaEJVa3AyUGNzc0RkUFRjVlVsK1JxdCtPMTRFQzBhVFBDQ1hFSwp4OUpvdC9SUlJCdWJJK25sVyswNndKUUlCSndidnZZWDFqOS8yNjJQQ2I3aTVTWkU5a0Ztb3BIL0F1dlkzeFBzCnQyOXFHRkh0NFRKYWFTeWlXcDFiT3Q1dDZnOHY5WnZUOGxKL295dkJISTVSQ3J1NUI4WXdHeUlRbWtvZVBwVkoKU1FQRzFEMElGK2tpbGxHb010czVUQ0FmZUlaeUFHZEZhb3NiSk96Z1lHUVI5VkFXZFRmSURQd3F2em1jc1VzWApqWU5pZW52K0xySzJNL2dXNmRPb25RUzZra3NjaUFPUFlXT2M3Y2xaUlJYa2JPRjkwa25hWXJib3ljcHlvbmxtCmU2NnFJNVpyOUxIc3ZpV3NHYitQd1B3TUt6KzdjbGpLWVlGd1JDQ3NWTUxoU2JNNElXRUN5a2tuT0J1OFROOCsKelNjTmpLL2hYZ0Q2bGM3QlJreVR0YkVVMzZCRzcxRHdsNVMxSXB5TXhiUHljdnRWaVRkYkEveXVLNVVuN3pBWAp2UzFIL0NrVVBUWStkbUZ0SmhlNEhkTXlTYkZqa2FzQzN2UzZZa2UxNWloejNBaWxBQ0cwbDZYanVLU1NRSWNRCjZOVGE4U3V0OXdkcFBOSUhPalV3S1prWVdjaGNhblkwck1HU044QjVWSCtqUWhHWVIzeHFKUjZqQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  auth:
    kubernetes:
      mountPath: "kubernetes-local"
      role: "external-secrets"
      serviceAccountRef:
        name: "external-secrets"
        namespace: "external-secrets"

externalSecrets:
- name: mongodb-7-secret-sync
  namespace: mongodb-7
  refreshInterval: 15m
  secretStoreRef:
    name: databases
    kind: ClusterSecretStore
  target:
    name: mongodb-7-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    templateType: Opaque
  data:
  - secretKey: mongodb-root-password
    remoteRef:
      key: mongodb-7
      property: root-password
  - secretKey: mongodb-passwords
    remoteRef:
      key: mongodb-7
      property: password
  - secretKey: mongodb-metrics-password
    remoteRef:
      key: mongodb-7
      property: metrics-password
  - secretKey: mongodb-replica-set-key
    remoteRef:
      key: mongodb-7
      property: replica-set-key
- name: mysql-51-secret-sync
  namespace: mysql-5-1-legacy
  refreshInterval: 15m
  secretStoreRef:
    name: databases
    kind: ClusterSecretStore
  target:
    name: mysql-51-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    templateType: Opaque
  data:
  - secretKey: mysql-root-password
    remoteRef:
      key: mysql-5.1
      property: root-password
  - secretKey: mysql-password
    remoteRef:
      key: mysql-5.1
      property: password
- name: redis-secret-sync
  namespace: redis
  refreshInterval: 15m
  secretStoreRef:
    name: databases
    kind: ClusterSecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    templateType: Opaque
  data:
  - secretKey: redis-password
    remoteRef:
      key: redis
      property: password
- name: postgresql-16-secret-sync
  namespace: postgresql-16
  refreshInterval: 15m
  secretStoreRef:
    name: databases
    kind: ClusterSecretStore
  target:
    name: postgresql-16-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    templateType: Opaque
  data:
  - secretKey: postgres-password
    remoteRef:
      key: postgresql-16
      property: postgres-password
  - secretKey: password
    remoteRef:
      key: postgresql-16
      property: password
  - secretKey: replication-password
    remoteRef:
      key: postgresql-16
      property: replication-password
  - secretKey: metrics-password
    remoteRef:
      key: postgresql-16
      property: metrics-password
- name: mysql-8-secret-sync
  namespace: mysql-8
  refreshInterval: 15m
  secretStoreRef:
    name: databases
    kind: ClusterSecretStore
  target:
    name: mysql-8-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    templateType: Opaque
  data:
  - secretKey: password
    remoteRef:
      key: mysql-8
      property: password
  - secretKey: replication-password
    remoteRef:
      key: mysql-8
      property: replication-password
  - secretKey: root-password
    remoteRef:
      key: mysql-8
      property: root-password
- name: mysql-5-7-secret-sync
  namespace: mysql-5-7
  refreshInterval: 15m
  secretStoreRef:
    name: databases
    kind: ClusterSecretStore
  target:
    name: mysql-5-7-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    templateType: Opaque
  data:
  - secretKey: password
    remoteRef:
      key: mysql-5.7
      property: password
  - secretKey: replication-password
    remoteRef:
      key: mysql-5.7
      property: replication-password
  - secretKey: root-password
    remoteRef:
      key: mysql-5.7
      property: root-password
